#.travis.yml
language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  slack: workablesolution:jYMnxwjbo0QJiy5R8HINdiDd
  # email:
  #   on_failure: change
  #   on_success: change
    